[package]
name = "rshtml_core"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
rust-version.workspace = true

[dependencies]
quote = "1.0.40"
proc-macro2 = { version = "1.0.95", features = ["span-locations"] }
syn = { version = "2.0.101", features = ["full", "visit", "visit-mut"] }
winnow = "0.7.14"
